#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
    remove|deconfigure)
        # Remove EC2 Instance Connect sshd override if present
        if status --quiet ssh && [ -f /etc/init/ssh.override ] ; then
            rm -f /etc/init/ssh.override
            echo "sshd override removed, restarting daemon..."
            initctl reload-configuration
            stop ssh || true
            start ssh
        fi

        # Remove EC2 Instance Connect sshd override if present
        if [ -f /lib/systemd/system/ssh.service.d/ec2-instance-connect.conf ] ; then
            rm -f /lib/systemd/system/ssh.service.d/ec2-instance-connect.conf
            if [ -z "$(ls -A /lib/systemd/system/ssh.service.d)" ] ; then
                # There were no other overrides, clean up
                rmdir /lib/systemd/system/ssh.service.d
            fi
            systemctl daemon-reload
            # Restart sshd
            echo "sshd override removed, restarting daemon..."
            deb-systemd-invoke restart ssh.service
        fi
    ;;
esac
